### ISSUE TITLE
Query parameters for tags

### ISSUE THREAD

**Issue by danfinlay** [state-of-the-dapps/sotd-www#103]
When adding/removing tags, you could append them to the URL as query params to allow users to share filters they enjoy.

Example:
`stateofthedapps.com?tags=metamask,live`

**Comment by robyedlin** [comment]
Hi @danfinlay! Thanks for submitting.

This is on the roadmap, so I'm going to mark it as a duplicate. Please see: https://github.com/state-of-the-dapps/sotd-www/issues/73
