### ISSUE TITLE
Add all acknowlegements to readme.

### ISSUE THREAD

**Issue by robyedlin** [state-of-the-dapps/sotd-www#23]

**Comment by robyedlin** [comment]
@jorisbontje can we get a list of all acknowledgments we want for the readme?

**Comment by jorisbontje** [comment]
Lets add @hitchcott for his original design:
https://github.com/state-of-the-dapps/state-of-the-dapps_old/issues/116#event-1262904031

**Comment by hitchcott** [comment]
Thanks @jorisbontje  👍

**Comment by robyedlin** [comment]
Hey @hitchcott, I linked to your website from the readme. LMK if you'd prefer a link to your github instead.

**Comment by robyedlin** [comment]
@jorisbontje Anyone else Joris?
