### ISSUE TITLE
Is it possible to sort by volume

### ISSUE THREAD

**Issue by davecraige** [state-of-the-dapps/sotd-www#278]
Love what you guys are building.  Props on all the work.🙌

Is it possible to sort by volume, maybe using USD or something as the main reference?  I think this would be a huge help.

**Comment by robyedlin** [comment]
Hi @davecraige ! Thanks for logging this issue. We have this on our internal roadmap, so I'm gonna close this here. If you don't see this resolved in a while, feel free to re-open.
