### ISSUE TITLE
Initials should be vertically centered

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#35]

**Comment by robyedlin** [comment]
Issue on android mobile.

**Comment by robyedlin** [comment]
@jorisbontje which devise/os/browser had this bug?

**Comment by jorisbontje** [comment]
Happens on my Samsung Galaxy S6 with Android 7.0 both in Chrome as well in Brave

**Comment by jorisbontje** [comment]
![screenshot_20171028-083656](https://user-images.githubusercontent.com/620959/32132031-1014d77a-bbbc-11e7-94d1-699dcd93dd7d.png)

**Comment by robyedlin** [comment]
Reproduced. Looks like it's an issue with how the font Overpass is rendered in Windows/Android. Will use a different method for vertical centering.

**Comment by jorisbontje** [comment]
Still the same

**Comment by robyedlin** [comment]
Whoops that commit made it worse. Hotfix coming.
