### ISSUE TITLE
Use slug algorithm for Dapp lookup by name

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#40]

**Comment by robyedlin** [comment]
Not sure what this means.

**Comment by jorisbontje** [comment]
In https://github.com/state-of-the-dapps/sotd-www/blob/master/components/submit/fields/Name.vue#L47 the `name` property is used as slug to test the existence of the DApp. However this might not be a match if there are any non alphanumeric characters in the DApp name (including spaces).

Ideally we'd have another endpoint for fuzzy lookup by name, or we'd implement a compatible slug algorithm client side as the one used server side (using the python library `slugify`).

**Comment by robyedlin** [comment]
What's an example mismatch?
