### ISSUE TITLE
Attribute mismatch testnet vs ropsten

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#41]

**Comment by robyedlin** [comment]
On the API docs.

**Comment by robyedlin** [comment]
Which endpoint is it?

**Comment by jorisbontje** [comment]
In https://github.com/state-of-the-dapps/sotd-www/blob/5322ba2838ee78dc4ec282e1a1cf6fbb98fe3fd9/store/submit.js#L39 the field is called `ropsten`, however in the API docs it is called `testnet`
http://docs.stateofthedappsapiv1.apiary.io/#reference/dapps/dapp-collection/create-dapp

**Comment by robyedlin** [comment]
Fixed in api https://github.com/state-of-the-dapps/docs_api_v1_stateofthedapps_com/commit/60435ba46c386b38458ef5cb3514228755ab6d58
