### ISSUE TITLE
Need reverse social images for the footer

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#43]
- reddit
- medium
- facebook
- slack

**Comment by robyedlin** [comment]
Looks like the site has these links without images, so now it's a bug. :)

**Comment by jorisbontje** [comment]
This is how it looks without icons:
![screen shot 2017-10-21 at 10 00 58](https://user-images.githubusercontent.com/620959/31849701-f2c6796e-b646-11e7-9025-4833301f586d.png)
