### ISSUE TITLE
Mixpanel "DApps - Detail popup" lacks dapp name attribute

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#44]
this makes it impossible to see on which dapp the user actually clicked.

**Comment by jorisbontje** [comment]
Probably best to add a `slug` attribute to all the events that are triggered from a Dapp detail / popup view. And/or are related to a specific dapp.

**Comment by robyedlin** [comment]
Will add `targetDapp` attribute.

**Comment by robyedlin** [comment]
Same should be applied to any 'DApps - Detail popup' events

**Comment by robyedlin** [comment]
Also applies to 'DApp - Related'
