### ISSUE TITLE
Upgrade connection to SSL

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#45]
When the user connects via http, we should upgrade to https.

**Comment by robyedlin** [comment]
It seems to be redirecting to https currently.

**Comment by robyedlin** [comment]
https://stateofthedapps.com/ will throw an error too. Every case should redirect to https://www.stateofthedapps.com

**Comment by jorisbontje** [comment]
This can be done using `redirect-ssl` with https://nuxtjs.org/api/configuration-servermiddleware/
