### ISSUE TITLE
Single mixpanel event for "DApp - View" with method as property

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#52]
"method" being the property name, and the value being "popup", "next", "prev", "related" or "direct" etc

**Comment by robyedlin** [comment]
..and to get rid of any event that duplicates DApp - View.

Is referral a referral site, or related DApp? If not related DApp, that's another value.

**Comment by jorisbontje** [comment]
Suggestion by Rob:
you sure you want to distinguish between next and prev?

can add a different prop for that
nav: prev
nav: next

**Comment by robyedlin** [comment]
Who's that Rob guy? :)

**Comment by robyedlin** [comment]
@jorisbontje referrer check is pretty unreliable.

**Comment by robyedlin** [comment]
Proposed strategy is to use vuex to:

1. store the mixpanel property in `viewMethod`
2. fire the mixpanel event
3. reset the `viewMethod` to `''`

If `viewMethod` is empty, then it's a "direct" hit, which could be a url typed in, or a referral link.

**Comment by jorisbontje** [comment]
Ah, I didn't mean `referral` but `related`. AKA when someone clicks on a DApp via the "Related ÐApps" section at the bottom of the DApp detail view.

**Comment by robyedlin** [comment]
Cool.
