### ISSUE TITLE
Newsletter signup on site

### ISSUE THREAD

**Issue by robyedlin** [state-of-the-dapps/sotd-www#54]

**Comment by robyedlin** [comment]
Just text "Get updates" will do.

**Comment by jorisbontje** [comment]
Mailerlite.com has all kinds of options for this; not sure which one you need, you have a login there though...

**Comment by robyedlin** [comment]
This will have to be the last addition to the header, due to space constraints. Otherwise will need a breakpoint change, or nav refactor.

<img width="1012" alt="screen shot 2017-10-25 at 4 40 33 pm" src="https://user-images.githubusercontent.com/10917203/32024760-4bccf4ca-b9a3-11e7-8338-9b12e5883b8c.png">

**Comment by jorisbontje** [comment]
Okay for now, but the subscribe form and thank you page should be hosted by us.

**Comment by jorisbontje** [comment]
New issue for follow up on form and thank you page: https://github.com/state-of-the-dapps/sotd-www/issues/100
