### ISSUE TITLE
Brave mobile "Whoops, an error occurred." when clicking on a dapp

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#55]
![2017-10-12 22 21 35](https://user-images.githubusercontent.com/620959/31534161-0916219e-aff6-11e7-843a-03baa18d14e2.png)

Happens when I click on some dapps, not on others; haven't found a pattern yet. Maybe as a side effect of blocked JS calls for Mixpanel / GA?

**Comment by jorisbontje** [comment]
This seems to happen on the DApp `adchain-registry` and be a side effect of ad blocking in Chrome  uBlock & Brave. 

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

Static filter `/adchain-` found in EasyList
https://easylist-downloads.adblockplus.org/easylist.txt

As far as I can tell we can't catch the `net::ERR_BLOCKED_BY_CLIENT` error explicitly, which would allow us to show a nicer error message.

**Comment by jorisbontje** [comment]
Fixed by renaming the slug

**Comment by robyedlin** [comment]
😎
