### ISSUE TITLE
Badges for Status and MetaMask compatibility

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#59]
Add badges for Status and MetaMask compatibility:
- `status-im`: show the status logo as badge https://status.im/img/new-site/logo3.png
- `metamask`: show the metamask logo as badge https://pbs.twimg.com/profile_images/632786773366599681/VzI4uiQB_400x400.png

**Comment by robyedlin** [comment]
https://github.com/state-of-the-dapps/sotd-www/commit/41108374a09975c7b78ab75caf2d2b66a5c29ef6

**Comment by robyedlin** [comment]
api should return 'status' and 'metamask' in the badges array.

**Comment by jorisbontje** [comment]
renamed `status` to `status-im`. otherwise great!
