### ISSUE TITLE
DApp in html head title undefined

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#66]
Looks like the SSR of the DApp name in the html head title isn't working correctly:
I'd expect to see the DApp name instead of `undefined`:

![screenshot 2017-10-17 18 26 25](https://user-images.githubusercontent.com/620959/31676695-b540ce68-b368-11e7-9c3d-deff6521ee96.png)

**Comment by jorisbontje** [comment]
This can be reproduced by pasting a link to a dapp in Slack; or by cmd clicking on a dapp in Chrome on OSX.

**Comment by robyedlin** [comment]
The DApp content (and therefore page title) is actually not loaded through the SSR `fetch` method due to https://github.com/state-of-the-dapps/sotd-www/issues/31#issuecomment-334840867

Will try removing the default title so that it won't change, and see if slack waits for the title to populate.

**Comment by jorisbontje** [comment]
Cant we use a mixed strategy lik this here?
https://github.com/nuxt/nuxt.js/issues/1071#issuecomment-314534576

**Comment by robyedlin** [comment]
Yep. https://github.com/state-of-the-dapps/sotd-www/commit/48c516ee390a4908f63088edcd48ea9abbff2246 did not resolve the issue. A modification of https://github.com/nuxt/nuxt.js/issues/1071#issuecomment-314534576 will fix it.

**Comment by jorisbontje** [comment]
Fixed!
