### ISSUE TITLE
On the submit page the width of the tag dropdown is too small (due to a small input field)

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#82]
![screen shot 2017-10-21 at 10 00 45](https://user-images.githubusercontent.com/620959/31849705-16bc627a-b647-11e7-8124-691f5036e4cd.png)

`348px` wide looks much better:

![screenshot 2017-10-21 10 07 24](https://user-images.githubusercontent.com/620959/31849733-abfe107c-b647-11e7-886d-75911e1d5487.png)

**Comment by robyedlin** [comment]
Nice dev tools manip. ;)

**Comment by robyedlin** [comment]
Add limit to 10 dapps and widen .
