### ISSUE TITLE
Add Sentry.io error tracking

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/sotd-www#83]
Possibly using https://github.com/nuxt-community/sentry-module

I have already created a project, ask me for the DSN.

**Comment by robyedlin** [comment]
@jorisbontje per your insight this will require node >6.

**Comment by jorisbontje** [comment]
@robyedlin I have created a PR for this, https://github.com/state-of-the-dapps/sotd-www/pull/104
and deployed it to https://sotd-todo.scalingo.io/
please check if you are okay with this.

**Comment by robyedlin** [comment]
@jorisbontje this is good now, yes?
